name: synapso
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # navigation
  go_router: ^11.1.4

  # state management
  mobx: ^2.2.0
  flutter_mobx: ^2.1.0
  provider: ^6.0.5
  
  # service locator / DI
  get_it: ^7.6.4

  # presentation packages
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.3
  awesome_extensions: ^2.0.9
  phone_form_field: ^8.1.0
  email_validator: ^2.1.17
  pinput: ^3.0.1
  carousel_slider: ^4.2.1
  
  # network
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  fresh_dio: ^0.4.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Hyundai Sans Head Office
      fonts: 
        - asset: assets/fonts/HyundaiSansHeadOffice-Regular.ttf
        - asset: assets/fonts/HyundaiSansHeadOffice-Light.ttf
        - asset: assets/fonts/HyundaiSansHeadOffice-Medium.ttf
        - asset: assets/fonts/HyundaiSansHeadOffice-Bold.ttf
          style: normal
